import { ArrowLeft, ArrowUpRight, BookOpen, Clock3, Grid2X2 } from 'lucide-react'
import { Link } from 'react-router-dom'

export function FuturePage({ kind }: { kind: 'history' | 'research' | 'missing' }) {
  const history = kind === 'history'
  const missing = kind === 'missing'
  const Icon = missing ? Grid2X2 : history ? Clock3 : BookOpen
  return <section className="future-page"><div className="eyebrow">{missing ? 'PAGE NOT FOUND' : 'PLANNED FOR PHASE 4'}</div><div className="future-layout"><div className="future-copy"><span className="future-icon"><Icon size={27} strokeWidth={1.2} /></span><h1>{missing ? 'A different direction.' : history ? 'A record of every review.' : 'Where evidence takes shape.'}</h1><p>{missing ? 'This page does not exist. Your sample workspace is one step away.' : history ? 'A considered space to find samples, revisit their images, and trace each interpretation.' : 'A dedicated view of the research behind the workspace: flat and staged designs, evaluated side by side.'}</p>{!missing && <div className="coming-note"><span className="phase-badge">Phase 4</span><span>{history ? 'Sample history has not been implemented yet.' : 'Experiment results have not been connected yet.'}</span></div>}<Link to="/workspace" className="button button-primary"><ArrowLeft size={16} />Back to workspace</Link></div><div className="future-art" aria-hidden="true"><img src="/assets/cell-etching.png" alt="" /><span>THE SCIENCE OF SEEING MORE</span></div></div>{!missing && <div className="future-feature-row">{(history ? ['Search by sample reference', 'Filter and revisit results', 'Trace model versions'] : ['Compare flat and staged designs', 'Inspect per-pattern performance', 'Measure expert agreement']).map(text => <span key={text}>{text}<ArrowUpRight size={15} /></span>)}</div>}</section>
}
